# Generated by Django 4.1 on 2022-09-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BOIS', 'Bois'), ('TERRE', 'Terre')], max_length=20, verbose_name='Ambiance')),
                ('date_start', models.DateField(default='1-09-2022')),
                ('date_end', models.DateField(default='1-09-2022')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
