# Generated by Django 4.1 on 2022-09-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambience', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambience',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ambience',
            name='date_start',
            field=models.DateField(),
        ),
    ]
