# Generated by Django 4.1 on 2022-09-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambience', '0003_alter_ambience_date_end_alter_ambience_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambience',
            name='date_end',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='ambience',
            name='date_start',
            field=models.DateField(verbose_name='Date de début'),
        ),
    ]
