# Generated by Django 4.1 on 2022-09-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambience', '0004_alter_ambience_date_end_alter_ambience_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambience',
            name='note',
            field=models.TextField(default='observations', verbose_name='Note'),
        ),
    ]
